### ISSUE TITLE
`ExperimentalData.showPtychogram` method fails

### ISSUE THREAD

**Issue by ShantanuKodgirwar** [PtyLab/PtyLab.py#42]
Legacy usage as `np.float` instead of `np.float32` for example below:

https://github.com/PtyLab/PtyLab.py/blob/889bf8fdcc3789e264d955a30b7972ce04953a65/PtyLab/ExperimentalData/ExperimentalData.py#LL229C65-L229C65

**Comment by dboonz** [comment]
Hi shanantu,

Thank you very much for all the hard work improving ptylab! I am at the moment unable to review it due to personal circumstances. I may be able to take a look in two weeks. @maisiedu, could you take a look?

Kind regards,

Dirk

On June 17, 2023 4:57:52 PM GMT+02:00, Shantanu Kodgirwar ***@***.***> wrote:
>Legacy usage as `np.float` instead of `np.float32` for example below:
>
>https://github.com/PtyLab/PtyLab.py/blob/889bf8fdcc3789e264d955a30b7972ce04953a65/PtyLab/ExperimentalData/ExperimentalData.py#LL229C65-L229C65
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/PtyLab/PtyLab.py/issues/42
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ShantanuKodgirwar** [comment]
No worries. I could also add a PR for this and @MaisieD could review and accept if okay.

**Comment by ShantanuKodgirwar** [comment]
This PR fixes it: https://github.com/PtyLab/PtyLab.py/pull/43
